### ISSUE TITLE
Feature request: Group buttons under submenus

### ISSUE THREAD

**Issue by lordekeen** [RivinHD/ScriptToButton#16]
For an easier organization if one has multiple buttons configured, would be nice if we can assign buttons under submenus (choosing their names as well). That way we can categorize scripts by theme/usage. The submenus could look like these example from AutoRig Pro:

![submenu example](https://github.com/RivinHD/ScriptToButton/assets/9127621/4944f15f-0384-45f7-8fa7-e7438509af84)
![submenu example 2](https://github.com/RivinHD/ScriptToButton/assets/9127621/bc63ec54-adc3-4a69-b459-c8dca1eb1247)

That way the addon can have a unique menu "Script to Buttons" with the options on top, and the buttons distributed under it across multiple group submenus, instead of two independent menus like it is now with the "Controls" and "Buttons". That makes it easier for those who use multiple addons and group them under specified tabs.

**Comment by RivinHD** [comment]
Fixed in Version 2.2.0
