### ISSUE TITLE
Can't change a property if script is not loaded to the Text Editor.

### ISSUE THREAD

**Issue by juliocargnin** [RivinHD/ScriptToButton#24]
**Describe the bug**
Can't change a property when running script if the script is not previously opened in the Text Editor.

**To Reproduce**
See this example that exactly shows the flaw:
https://od.lk/s/MjBfMjcwMzMwOTVf/script-to-button_BUG.mp4

**Version Information:**
 - Add-on Version: 2.2.1
 - Blender Version: 3.6.5

**Comment by RivinHD** [comment]
Thanks for reporting. This is fixed in [Version 2.2.2](https://github.com/RivinHD/ScriptToButton/releases/tag/v2.2.2).
Sorry that it took so long to fix this error.
