### ISSUE TITLE
Not able to export scripts to files in 2.93.5

### ISSUE THREAD

**Issue by Taroslord** [RivinHD/ScriptToButton#3]
Exporting scripts as Python files doesn't work.
Error: "The given filepath is not a dirctory"

Exporting ZIP files works as expected. All Python scripts are zipped and can be viewed in code editors.

Tested in Blender 2.93.5

**Comment by RivinHD** [comment]
Solved in Version 2.1.3

**Comment by Taroslord** [comment]
Looks good so far!
Thank you!
