### ISSUE TITLE
Sort scripts alphanumerically

### ISSUE THREAD

**Issue by qwiff-dogg** [RivinHD/ScriptToButton#9]
**Is your feature request related to a problem? Please describe.**
The add-on lists scripts in the order in which `listdir` provides them.

**Describe the solution you'd like**
Rather than leave the order undefined, it would be better if the scripts were ordered alphanumerically. This way the user can  group/order scripts based on the filename.

**Additional context**
Adding `l.sort()` before returning in https://github.com/RivinHD/ScriptToButton/blob/master/functions.py#L38 seems to address the issue for me.

**Comment by RivinHD** [comment]
Ok, will be added in the next version :)

**Comment by RivinHD** [comment]
Fixed with [Version 2.1.6](https://github.com/RivinHD/ScriptToButton/releases/tag/v2.1.6)
